source 'https://rubygems.org'


gem 'sinatra'
gem 'thin'
gem 'rack'
gem 'activerecord'
gem 'sinatra-flash'
gem 'warden'
gem 'haml'

group :development do
  gem 'awesome_print'
  gem 'shotgun'
  gem 'yard'
  gem 'rdiscount'
end

group :test do
  gem 'rack-test'
  gem 'capybara-webkit'
end
